<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0.00_text-22-0-0-1</name>
   <tag></tag>
   <elementGuidId>90ab5cb6-bc48-4dee-bbaf-3c741c65f146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-22-0-0-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='text-22-0-0-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c510b0c-36d7-40b4-9d55-ea2649f2046d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-22-0-0-1</value>
      <webElementGuid>c61f9c20-90c6-4fcc-9837-b7384d03f74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module module-text text-22-0-0-1   </value>
      <webElementGuid>158e9322-70aa-45c4-999d-04e8198cb487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-22-0-0-1&quot;)</value>
      <webElementGuid>0002c36c-63d3-4daf-9d8f-63eda86f39ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='text-22-0-0-1']</value>
      <webElementGuid>73dc265b-a59c-4ae7-90a9-f6ee63bb3efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='themify_builder_content-22']/div/div/div/div/div/div</value>
      <webElementGuid>fbdf23d0-e025-47a3-b2c0-b7477b27fb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹0.00'])[1]/following::div[34]</value>
      <webElementGuid>68eb0c4e-c099-4c2c-ac7a-e1ec27c18574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::div[34]</value>
      <webElementGuid>55004588-5e3b-4977-a20d-e60a5985ab8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new arrivals'])[1]/preceding::div[20]</value>
      <webElementGuid>9437bc00-89b9-4136-8333-60bec7bd4a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Ruby'])[1]/preceding::div[24]</value>
      <webElementGuid>b054b394-cd90-44df-a1fd-f5b0295f36a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>1af76fa8-2b6d-476f-8d65-ee3181e39dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'text-22-0-0-1']</value>
      <webElementGuid>b6dd5b83-9de0-448e-b9cb-ba86550e4bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
