<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sort_date_first_book</name>
   <tag></tag>
   <elementGuidId>5712f0b4-f8ee-4fcd-9444-487aab905b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h3)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
