<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_single</name>
   <tag></tag>
   <elementGuidId>8106fa99-b131-428e-8c8f-5a4756c20284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'billing_country']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_country</value>
      <webElementGuid>babb905e-3bb7-4f46-a983-71de17a81f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_country</value>
      <webElementGuid>0770f9e9-e17a-4833-86da-cbad74e659e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='test']</value>
      <webElementGuid>d47a6b47-ecec-4b08-b59c-d3119a81986e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
