<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemQuantity</name>
   <tag></tag>
   <elementGuidId>70934f26-8620-4532-9180-a1d9347dd8f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='cartcontents']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>class</value>
      <webElementGuid>5c380798-ee91-4aec-a571-bbf8602c6fad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
